### ISSUE TITLE
Unable to install - QuickLootIE-2.0.0-Canary

### ISSUE THREAD

**Issue by arturooteruelo** [JanuarySnow/Desolation#1]
The mod link is not available anymore:
[FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download QuickLootIE-2.0.0-Canary.zip (HTTPDownloader+State|https://github.com/MissCorruption/QuickLootIE/releases/download/2.0.0-Canary/QuickLootIE-2.0.0-Canary.zip)

**Comment by JanuarySnow** [comment]
Fixed now in 0.3 - the nexus page has been updated and I guess that GH canary release got deleted, so im using the nexus page now.

**Comment by arturooteruelo** [comment]
Yep, it's installing now.
Thanks.
